// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"context"

	"github.com/mvcris/maya-guessr/backend/internal/core/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocationRepository creates a new instance of MockLocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationRepository {
	mock := &MockLocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocationRepository is an autogenerated mock type for the LocationRepository type
type MockLocationRepository struct {
	mock.Mock
}

type MockLocationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationRepository) EXPECT() *MockLocationRepository_Expecter {
	return &MockLocationRepository_Expecter{mock: &_m.Mock}
}

// CountByMapId provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) CountByMapId(ctx context.Context, mapId string) (int64, error) {
	ret := _mock.Called(ctx, mapId)

	if len(ret) == 0 {
		panic("no return value specified for CountByMapId")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, mapId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, mapId)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, mapId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocationRepository_CountByMapId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByMapId'
type MockLocationRepository_CountByMapId_Call struct {
	*mock.Call
}

// CountByMapId is a helper method to define mock.On call
//   - ctx context.Context
//   - mapId string
func (_e *MockLocationRepository_Expecter) CountByMapId(ctx interface{}, mapId interface{}) *MockLocationRepository_CountByMapId_Call {
	return &MockLocationRepository_CountByMapId_Call{Call: _e.mock.On("CountByMapId", ctx, mapId)}
}

func (_c *MockLocationRepository_CountByMapId_Call) Run(run func(ctx context.Context, mapId string)) *MockLocationRepository_CountByMapId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocationRepository_CountByMapId_Call) Return(n int64, err error) *MockLocationRepository_CountByMapId_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLocationRepository_CountByMapId_Call) RunAndReturn(run func(ctx context.Context, mapId string) (int64, error)) *MockLocationRepository_CountByMapId_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) Create(ctx context.Context, l *entities.Location) error {
	ret := _mock.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Location) error); ok {
		r0 = returnFunc(ctx, l)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLocationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - l *entities.Location
func (_e *MockLocationRepository_Expecter) Create(ctx interface{}, l interface{}) *MockLocationRepository_Create_Call {
	return &MockLocationRepository_Create_Call{Call: _e.mock.On("Create", ctx, l)}
}

func (_c *MockLocationRepository_Create_Call) Run(run func(ctx context.Context, l *entities.Location)) *MockLocationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Location
		if args[1] != nil {
			arg1 = args[1].(*entities.Location)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocationRepository_Create_Call) Return(err error) *MockLocationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, l *entities.Location) error) *MockLocationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindRandomLocationByMapId provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) FindRandomLocationByMapId(ctx context.Context, mapId string, quantity int) ([]*entities.Location, error) {
	ret := _mock.Called(ctx, mapId, quantity)

	if len(ret) == 0 {
		panic("no return value specified for FindRandomLocationByMapId")
	}

	var r0 []*entities.Location
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]*entities.Location, error)); ok {
		return returnFunc(ctx, mapId, quantity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []*entities.Location); ok {
		r0 = returnFunc(ctx, mapId, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Location)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, mapId, quantity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocationRepository_FindRandomLocationByMapId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRandomLocationByMapId'
type MockLocationRepository_FindRandomLocationByMapId_Call struct {
	*mock.Call
}

// FindRandomLocationByMapId is a helper method to define mock.On call
//   - ctx context.Context
//   - mapId string
//   - quantity int
func (_e *MockLocationRepository_Expecter) FindRandomLocationByMapId(ctx interface{}, mapId interface{}, quantity interface{}) *MockLocationRepository_FindRandomLocationByMapId_Call {
	return &MockLocationRepository_FindRandomLocationByMapId_Call{Call: _e.mock.On("FindRandomLocationByMapId", ctx, mapId, quantity)}
}

func (_c *MockLocationRepository_FindRandomLocationByMapId_Call) Run(run func(ctx context.Context, mapId string, quantity int)) *MockLocationRepository_FindRandomLocationByMapId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLocationRepository_FindRandomLocationByMapId_Call) Return(locations []*entities.Location, err error) *MockLocationRepository_FindRandomLocationByMapId_Call {
	_c.Call.Return(locations, err)
	return _c
}

func (_c *MockLocationRepository_FindRandomLocationByMapId_Call) RunAndReturn(run func(ctx context.Context, mapId string, quantity int) ([]*entities.Location, error)) *MockLocationRepository_FindRandomLocationByMapId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMapRepository creates a new instance of MockMapRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMapRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMapRepository {
	mock := &MockMapRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMapRepository is an autogenerated mock type for the MapRepository type
type MockMapRepository struct {
	mock.Mock
}

type MockMapRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMapRepository) EXPECT() *MockMapRepository_Expecter {
	return &MockMapRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) Create(ctx context.Context, m *entities.Map) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Map) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMapRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMapRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *entities.Map
func (_e *MockMapRepository_Expecter) Create(ctx interface{}, m interface{}) *MockMapRepository_Create_Call {
	return &MockMapRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockMapRepository_Create_Call) Run(run func(ctx context.Context, m *entities.Map)) *MockMapRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Map
		if args[1] != nil {
			arg1 = args[1].(*entities.Map)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMapRepository_Create_Call) Return(err error) *MockMapRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMapRepository_Create_Call) RunAndReturn(run func(ctx context.Context, m *entities.Map) error) *MockMapRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) FindByName(ctx context.Context, name string) (*entities.Map, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entities.Map
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Map, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Map); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Map)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMapRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockMapRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockMapRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockMapRepository_FindByName_Call {
	return &MockMapRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockMapRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockMapRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMapRepository_FindByName_Call) Return(mapParam *entities.Map, err error) *MockMapRepository_FindByName_Call {
	_c.Call.Return(mapParam, err)
	return _c
}

func (_c *MockMapRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*entities.Map, error)) *MockMapRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) Create(ctx context.Context, refreshToken *entities.RefreshToken) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.RefreshToken) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken *entities.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(ctx interface{}, refreshToken interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, refreshToken)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, refreshToken *entities.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*entities.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(err error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, refreshToken *entities.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) FindById(ctx context.Context, id string) (*entities.RefreshToken, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.RefreshToken, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.RefreshToken); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRefreshTokenRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRefreshTokenRepository_Expecter) FindById(ctx interface{}, id interface{}) *MockRefreshTokenRepository_FindById_Call {
	return &MockRefreshTokenRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockRefreshTokenRepository_FindById_Call) Run(run func(ctx context.Context, id string)) *MockRefreshTokenRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindById_Call) Return(refreshToken *entities.RefreshToken, err error) *MockRefreshTokenRepository_FindById_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepository_FindById_Call) RunAndReturn(run func(ctx context.Context, id string) (*entities.RefreshToken, error)) *MockRefreshTokenRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) Update(ctx context.Context, refreshToken *entities.RefreshToken) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.RefreshToken) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRefreshTokenRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken *entities.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Update(ctx interface{}, refreshToken interface{}) *MockRefreshTokenRepository_Update_Call {
	return &MockRefreshTokenRepository_Update_Call{Call: _e.mock.On("Update", ctx, refreshToken)}
}

func (_c *MockRefreshTokenRepository_Update_Call) Run(run func(ctx context.Context, refreshToken *entities.RefreshToken)) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*entities.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Update_Call) Return(err error) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_Update_Call) RunAndReturn(run func(ctx context.Context, refreshToken *entities.RefreshToken) error) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSinglePlayerGameRepository creates a new instance of MockSinglePlayerGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSinglePlayerGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSinglePlayerGameRepository {
	mock := &MockSinglePlayerGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSinglePlayerGameRepository is an autogenerated mock type for the SinglePlayerGameRepository type
type MockSinglePlayerGameRepository struct {
	mock.Mock
}

type MockSinglePlayerGameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSinglePlayerGameRepository) EXPECT() *MockSinglePlayerGameRepository_Expecter {
	return &MockSinglePlayerGameRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSinglePlayerGameRepository
func (_mock *MockSinglePlayerGameRepository) Create(ctx context.Context, game *entities.SinglePlayerGame) error {
	ret := _mock.Called(ctx, game)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.SinglePlayerGame) error); ok {
		r0 = returnFunc(ctx, game)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSinglePlayerGameRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSinglePlayerGameRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - game *entities.SinglePlayerGame
func (_e *MockSinglePlayerGameRepository_Expecter) Create(ctx interface{}, game interface{}) *MockSinglePlayerGameRepository_Create_Call {
	return &MockSinglePlayerGameRepository_Create_Call{Call: _e.mock.On("Create", ctx, game)}
}

func (_c *MockSinglePlayerGameRepository_Create_Call) Run(run func(ctx context.Context, game *entities.SinglePlayerGame)) *MockSinglePlayerGameRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.SinglePlayerGame
		if args[1] != nil {
			arg1 = args[1].(*entities.SinglePlayerGame)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSinglePlayerGameRepository_Create_Call) Return(err error) *MockSinglePlayerGameRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSinglePlayerGameRepository_Create_Call) RunAndReturn(run func(ctx context.Context, game *entities.SinglePlayerGame) error) *MockSinglePlayerGameRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdAndUserIdWithLock provides a mock function for the type MockSinglePlayerGameRepository
func (_mock *MockSinglePlayerGameRepository) FindByIdAndUserIdWithLock(ctx context.Context, id string, userId string) (*entities.SinglePlayerGame, error) {
	ret := _mock.Called(ctx, id, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdAndUserIdWithLock")
	}

	var r0 *entities.SinglePlayerGame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entities.SinglePlayerGame, error)); ok {
		return returnFunc(ctx, id, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entities.SinglePlayerGame); ok {
		r0 = returnFunc(ctx, id, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.SinglePlayerGame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdAndUserIdWithLock'
type MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call struct {
	*mock.Call
}

// FindByIdAndUserIdWithLock is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userId string
func (_e *MockSinglePlayerGameRepository_Expecter) FindByIdAndUserIdWithLock(ctx interface{}, id interface{}, userId interface{}) *MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call {
	return &MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call{Call: _e.mock.On("FindByIdAndUserIdWithLock", ctx, id, userId)}
}

func (_c *MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call) Run(run func(ctx context.Context, id string, userId string)) *MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call) Return(singlePlayerGame *entities.SinglePlayerGame, err error) *MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call {
	_c.Call.Return(singlePlayerGame, err)
	return _c
}

func (_c *MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call) RunAndReturn(run func(ctx context.Context, id string, userId string) (*entities.SinglePlayerGame, error)) *MockSinglePlayerGameRepository_FindByIdAndUserIdWithLock_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserIdAndStatuses provides a mock function for the type MockSinglePlayerGameRepository
func (_mock *MockSinglePlayerGameRepository) FindByUserIdAndStatuses(ctx context.Context, userId string, statuses []entities.SinglePlayerGameStatus) (*entities.SinglePlayerGame, error) {
	ret := _mock.Called(ctx, userId, statuses)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIdAndStatuses")
	}

	var r0 *entities.SinglePlayerGame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []entities.SinglePlayerGameStatus) (*entities.SinglePlayerGame, error)); ok {
		return returnFunc(ctx, userId, statuses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []entities.SinglePlayerGameStatus) *entities.SinglePlayerGame); ok {
		r0 = returnFunc(ctx, userId, statuses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.SinglePlayerGame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []entities.SinglePlayerGameStatus) error); ok {
		r1 = returnFunc(ctx, userId, statuses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserIdAndStatuses'
type MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call struct {
	*mock.Call
}

// FindByUserIdAndStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - statuses []entities.SinglePlayerGameStatus
func (_e *MockSinglePlayerGameRepository_Expecter) FindByUserIdAndStatuses(ctx interface{}, userId interface{}, statuses interface{}) *MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call {
	return &MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call{Call: _e.mock.On("FindByUserIdAndStatuses", ctx, userId, statuses)}
}

func (_c *MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call) Run(run func(ctx context.Context, userId string, statuses []entities.SinglePlayerGameStatus)) *MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []entities.SinglePlayerGameStatus
		if args[2] != nil {
			arg2 = args[2].([]entities.SinglePlayerGameStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call) Return(singlePlayerGame *entities.SinglePlayerGame, err error) *MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call {
	_c.Call.Return(singlePlayerGame, err)
	return _c
}

func (_c *MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call) RunAndReturn(run func(ctx context.Context, userId string, statuses []entities.SinglePlayerGameStatus) (*entities.SinglePlayerGame, error)) *MockSinglePlayerGameRepository_FindByUserIdAndStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSinglePlayerGameRepository
func (_mock *MockSinglePlayerGameRepository) Update(ctx context.Context, game *entities.SinglePlayerGame) error {
	ret := _mock.Called(ctx, game)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.SinglePlayerGame) error); ok {
		r0 = returnFunc(ctx, game)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSinglePlayerGameRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSinglePlayerGameRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - game *entities.SinglePlayerGame
func (_e *MockSinglePlayerGameRepository_Expecter) Update(ctx interface{}, game interface{}) *MockSinglePlayerGameRepository_Update_Call {
	return &MockSinglePlayerGameRepository_Update_Call{Call: _e.mock.On("Update", ctx, game)}
}

func (_c *MockSinglePlayerGameRepository_Update_Call) Run(run func(ctx context.Context, game *entities.SinglePlayerGame)) *MockSinglePlayerGameRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.SinglePlayerGame
		if args[1] != nil {
			arg1 = args[1].(*entities.SinglePlayerGame)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSinglePlayerGameRepository_Update_Call) Return(err error) *MockSinglePlayerGameRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSinglePlayerGameRepository_Update_Call) RunAndReturn(run func(ctx context.Context, game *entities.SinglePlayerGame) error) *MockSinglePlayerGameRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSinglePlayerRoundRepository creates a new instance of MockSinglePlayerRoundRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSinglePlayerRoundRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSinglePlayerRoundRepository {
	mock := &MockSinglePlayerRoundRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSinglePlayerRoundRepository is an autogenerated mock type for the SinglePlayerRoundRepository type
type MockSinglePlayerRoundRepository struct {
	mock.Mock
}

type MockSinglePlayerRoundRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSinglePlayerRoundRepository) EXPECT() *MockSinglePlayerRoundRepository_Expecter {
	return &MockSinglePlayerRoundRepository_Expecter{mock: &_m.Mock}
}

// FindByGameIdAndRoundNumberWithLock provides a mock function for the type MockSinglePlayerRoundRepository
func (_mock *MockSinglePlayerRoundRepository) FindByGameIdAndRoundNumberWithLock(ctx context.Context, gameId string, roundNumber int) (*entities.SinglePlayerRound, error) {
	ret := _mock.Called(ctx, gameId, roundNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindByGameIdAndRoundNumberWithLock")
	}

	var r0 *entities.SinglePlayerRound
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (*entities.SinglePlayerRound, error)); ok {
		return returnFunc(ctx, gameId, roundNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) *entities.SinglePlayerRound); ok {
		r0 = returnFunc(ctx, gameId, roundNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.SinglePlayerRound)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, gameId, roundNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByGameIdAndRoundNumberWithLock'
type MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call struct {
	*mock.Call
}

// FindByGameIdAndRoundNumberWithLock is a helper method to define mock.On call
//   - ctx context.Context
//   - gameId string
//   - roundNumber int
func (_e *MockSinglePlayerRoundRepository_Expecter) FindByGameIdAndRoundNumberWithLock(ctx interface{}, gameId interface{}, roundNumber interface{}) *MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call {
	return &MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call{Call: _e.mock.On("FindByGameIdAndRoundNumberWithLock", ctx, gameId, roundNumber)}
}

func (_c *MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call) Run(run func(ctx context.Context, gameId string, roundNumber int)) *MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call) Return(singlePlayerRound *entities.SinglePlayerRound, err error) *MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call {
	_c.Call.Return(singlePlayerRound, err)
	return _c
}

func (_c *MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call) RunAndReturn(run func(ctx context.Context, gameId string, roundNumber int) (*entities.SinglePlayerRound, error)) *MockSinglePlayerRoundRepository_FindByGameIdAndRoundNumberWithLock_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdAndGameIdWithLock provides a mock function for the type MockSinglePlayerRoundRepository
func (_mock *MockSinglePlayerRoundRepository) FindByIdAndGameIdWithLock(ctx context.Context, id string, gameId string) (*entities.SinglePlayerRound, error) {
	ret := _mock.Called(ctx, id, gameId)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdAndGameIdWithLock")
	}

	var r0 *entities.SinglePlayerRound
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entities.SinglePlayerRound, error)); ok {
		return returnFunc(ctx, id, gameId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entities.SinglePlayerRound); ok {
		r0 = returnFunc(ctx, id, gameId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.SinglePlayerRound)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, gameId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdAndGameIdWithLock'
type MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call struct {
	*mock.Call
}

// FindByIdAndGameIdWithLock is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - gameId string
func (_e *MockSinglePlayerRoundRepository_Expecter) FindByIdAndGameIdWithLock(ctx interface{}, id interface{}, gameId interface{}) *MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call {
	return &MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call{Call: _e.mock.On("FindByIdAndGameIdWithLock", ctx, id, gameId)}
}

func (_c *MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call) Run(run func(ctx context.Context, id string, gameId string)) *MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call) Return(singlePlayerRound *entities.SinglePlayerRound, err error) *MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call {
	_c.Call.Return(singlePlayerRound, err)
	return _c
}

func (_c *MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call) RunAndReturn(run func(ctx context.Context, id string, gameId string) (*entities.SinglePlayerRound, error)) *MockSinglePlayerRoundRepository_FindByIdAndGameIdWithLock_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSinglePlayerRoundRepository
func (_mock *MockSinglePlayerRoundRepository) Update(ctx context.Context, round *entities.SinglePlayerRound) error {
	ret := _mock.Called(ctx, round)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.SinglePlayerRound) error); ok {
		r0 = returnFunc(ctx, round)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSinglePlayerRoundRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSinglePlayerRoundRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - round *entities.SinglePlayerRound
func (_e *MockSinglePlayerRoundRepository_Expecter) Update(ctx interface{}, round interface{}) *MockSinglePlayerRoundRepository_Update_Call {
	return &MockSinglePlayerRoundRepository_Update_Call{Call: _e.mock.On("Update", ctx, round)}
}

func (_c *MockSinglePlayerRoundRepository_Update_Call) Run(run func(ctx context.Context, round *entities.SinglePlayerRound)) *MockSinglePlayerRoundRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.SinglePlayerRound
		if args[1] != nil {
			arg1 = args[1].(*entities.SinglePlayerRound)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSinglePlayerRoundRepository_Update_Call) Return(err error) *MockSinglePlayerRoundRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSinglePlayerRoundRepository_Update_Call) RunAndReturn(run func(ctx context.Context, round *entities.SinglePlayerRound) error) *MockSinglePlayerRoundRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, user *entities.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user *entities.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.User
		if args[1] != nil {
			arg1 = args[1].(*entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(err error) *MockUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByEmail(ctx context.Context, email string) (*entities.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepository_FindByEmail_Call {
	return &MockUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) Return(user *entities.User, err error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entities.User, error)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindById(ctx context.Context, id string) (*entities.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockUserRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) FindById(ctx interface{}, id interface{}) *MockUserRepository_FindById_Call {
	return &MockUserRepository_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockUserRepository_FindById_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindById_Call) Return(user *entities.User, err error) *MockUserRepository_FindById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindById_Call) RunAndReturn(run func(ctx context.Context, id string) (*entities.User, error)) *MockUserRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByUsername(ctx context.Context, username string) (*entities.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepository_Expecter) FindByUsername(ctx interface{}, username interface{}) *MockUserRepository_FindByUsername_Call {
	return &MockUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockUserRepository_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) Return(user *entities.User, err error) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*entities.User, error)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}
