// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositories

import (
	"github.com/mvcris/maya-guessr/backend/internal/core/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocationRepository creates a new instance of MockLocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationRepository {
	mock := &MockLocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocationRepository is an autogenerated mock type for the LocationRepository type
type MockLocationRepository struct {
	mock.Mock
}

type MockLocationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationRepository) EXPECT() *MockLocationRepository_Expecter {
	return &MockLocationRepository_Expecter{mock: &_m.Mock}
}

// CountByMapId provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) CountByMapId(mapId string) (int64, error) {
	ret := _mock.Called(mapId)

	if len(ret) == 0 {
		panic("no return value specified for CountByMapId")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(mapId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(mapId)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(mapId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocationRepository_CountByMapId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByMapId'
type MockLocationRepository_CountByMapId_Call struct {
	*mock.Call
}

// CountByMapId is a helper method to define mock.On call
//   - mapId string
func (_e *MockLocationRepository_Expecter) CountByMapId(mapId interface{}) *MockLocationRepository_CountByMapId_Call {
	return &MockLocationRepository_CountByMapId_Call{Call: _e.mock.On("CountByMapId", mapId)}
}

func (_c *MockLocationRepository_CountByMapId_Call) Run(run func(mapId string)) *MockLocationRepository_CountByMapId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocationRepository_CountByMapId_Call) Return(n int64, err error) *MockLocationRepository_CountByMapId_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLocationRepository_CountByMapId_Call) RunAndReturn(run func(mapId string) (int64, error)) *MockLocationRepository_CountByMapId_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockLocationRepository
func (_mock *MockLocationRepository) Create(l *entities.Location) error {
	ret := _mock.Called(l)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entities.Location) error); ok {
		r0 = returnFunc(l)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLocationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLocationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - l *entities.Location
func (_e *MockLocationRepository_Expecter) Create(l interface{}) *MockLocationRepository_Create_Call {
	return &MockLocationRepository_Create_Call{Call: _e.mock.On("Create", l)}
}

func (_c *MockLocationRepository_Create_Call) Run(run func(l *entities.Location)) *MockLocationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.Location
		if args[0] != nil {
			arg0 = args[0].(*entities.Location)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLocationRepository_Create_Call) Return(err error) *MockLocationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLocationRepository_Create_Call) RunAndReturn(run func(l *entities.Location) error) *MockLocationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMapRepository creates a new instance of MockMapRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMapRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMapRepository {
	mock := &MockMapRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMapRepository is an autogenerated mock type for the MapRepository type
type MockMapRepository struct {
	mock.Mock
}

type MockMapRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMapRepository) EXPECT() *MockMapRepository_Expecter {
	return &MockMapRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) Create(m *entities.Map) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entities.Map) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMapRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMapRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - m *entities.Map
func (_e *MockMapRepository_Expecter) Create(m interface{}) *MockMapRepository_Create_Call {
	return &MockMapRepository_Create_Call{Call: _e.mock.On("Create", m)}
}

func (_c *MockMapRepository_Create_Call) Run(run func(m *entities.Map)) *MockMapRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.Map
		if args[0] != nil {
			arg0 = args[0].(*entities.Map)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMapRepository_Create_Call) Return(err error) *MockMapRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMapRepository_Create_Call) RunAndReturn(run func(m *entities.Map) error) *MockMapRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockMapRepository
func (_mock *MockMapRepository) FindByName(name string) (*entities.Map, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entities.Map
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entities.Map, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entities.Map); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Map)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMapRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockMapRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - name string
func (_e *MockMapRepository_Expecter) FindByName(name interface{}) *MockMapRepository_FindByName_Call {
	return &MockMapRepository_FindByName_Call{Call: _e.mock.On("FindByName", name)}
}

func (_c *MockMapRepository_FindByName_Call) Run(run func(name string)) *MockMapRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMapRepository_FindByName_Call) Return(mapParam *entities.Map, err error) *MockMapRepository_FindByName_Call {
	_c.Call.Return(mapParam, err)
	return _c
}

func (_c *MockMapRepository_FindByName_Call) RunAndReturn(run func(name string) (*entities.Map, error)) *MockMapRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) Create(refreshToken *entities.RefreshToken) error {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entities.RefreshToken) error); ok {
		r0 = returnFunc(refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - refreshToken *entities.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(refreshToken interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", refreshToken)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(refreshToken *entities.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.RefreshToken
		if args[0] != nil {
			arg0 = args[0].(*entities.RefreshToken)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(err error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(refreshToken *entities.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) FindById(id string) (*entities.RefreshToken, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entities.RefreshToken, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entities.RefreshToken); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRefreshTokenRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id string
func (_e *MockRefreshTokenRepository_Expecter) FindById(id interface{}) *MockRefreshTokenRepository_FindById_Call {
	return &MockRefreshTokenRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockRefreshTokenRepository_FindById_Call) Run(run func(id string)) *MockRefreshTokenRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindById_Call) Return(refreshToken *entities.RefreshToken, err error) *MockRefreshTokenRepository_FindById_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenRepository_FindById_Call) RunAndReturn(run func(id string) (*entities.RefreshToken, error)) *MockRefreshTokenRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRefreshTokenRepository
func (_mock *MockRefreshTokenRepository) Update(refreshToken *entities.RefreshToken) error {
	ret := _mock.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entities.RefreshToken) error); ok {
		r0 = returnFunc(refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRefreshTokenRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - refreshToken *entities.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Update(refreshToken interface{}) *MockRefreshTokenRepository_Update_Call {
	return &MockRefreshTokenRepository_Update_Call{Call: _e.mock.On("Update", refreshToken)}
}

func (_c *MockRefreshTokenRepository_Update_Call) Run(run func(refreshToken *entities.RefreshToken)) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.RefreshToken
		if args[0] != nil {
			arg0 = args[0].(*entities.RefreshToken)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Update_Call) Return(err error) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenRepository_Update_Call) RunAndReturn(run func(refreshToken *entities.RefreshToken) error) *MockRefreshTokenRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(user *entities.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entities.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *entities.User
func (_e *MockUserRepository_Expecter) Create(user interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(user *entities.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.User
		if args[0] != nil {
			arg0 = args[0].(*entities.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(err error) *MockUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(user *entities.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByEmail(email string) (*entities.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entities.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entities.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserRepository_Expecter) FindByEmail(email interface{}) *MockUserRepository_FindByEmail_Call {
	return &MockUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *MockUserRepository_FindByEmail_Call) Run(run func(email string)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) Return(user *entities.User, err error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) RunAndReturn(run func(email string) (*entities.User, error)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindById(id string) (*entities.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entities.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entities.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockUserRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id string
func (_e *MockUserRepository_Expecter) FindById(id interface{}) *MockUserRepository_FindById_Call {
	return &MockUserRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockUserRepository_FindById_Call) Run(run func(id string)) *MockUserRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindById_Call) Return(user *entities.User, err error) *MockUserRepository_FindById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindById_Call) RunAndReturn(run func(id string) (*entities.User, error)) *MockUserRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByUsername(username string) (*entities.User, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*entities.User, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entities.User); ok {
		r0 = returnFunc(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockUserRepository_Expecter) FindByUsername(username interface{}) *MockUserRepository_FindByUsername_Call {
	return &MockUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", username)}
}

func (_c *MockUserRepository_FindByUsername_Call) Run(run func(username string)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) Return(user *entities.User, err error) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) RunAndReturn(run func(username string) (*entities.User, error)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}
